Feature/signup
wecode-bootcamp-korea/32-2nd-CannotSleepSeoul-backend pull request #2
Opened 2022-05-12 12:24 UTC by alexms0316

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카카오 소셜 로그인

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 카카오 소셜 로그인 view 구현
- post명령어를 사용하여 CSS 데이터베이스에도 user정보 저장

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- get method만 사용가능할 것이라 생각하고 시작했는데, post method를 사용하여 CSS 데이터베이스에 유저의 정보까지 저장할 수 있게 되었음.

<br />

## :: 기타 질문 및 특이 사항
- 없음.

2022-05-15 06:38 UTC, Kang-kyunghun requested changes

2022-05-15 06:38 UTC, Kang-kyunghun commented on users/urls.py
> +    path('/kakaosignin', KakaoSignIn.as_view()),
```suggestion
    path('/signin/kakao', KakaoSignIn.as_view()),
```

2022-05-15 06:38 UTC, Kang-kyunghun commented on users/views.py
> +from datetime     import datetime, timedelta
package import convention에 맞게 수정해 주세요.

2022-05-15 06:38 UTC, Kang-kyunghun commented on users/views.py
> +            user_info_response = requests.get(kakao_info_api,headers=headers, timeout=5)
```suggestion
            response = requests.get(kakao_info_api,headers=headers, timeout=5)
```
1. requests를 사용할 때 timeout 부여해 주신 점 잘 하셨습니다.
2. requests를 여러번 사용하는 것이 아니므로 그냥 response로도 충분할 것 같습니다.
3. 되도록 info처럼 줄임말 사용은 자제해 주세요.

2022-05-15 06:38 UTC, Kang-kyunghun commented on users/views.py
> +            id                 = user_info['id']
```suggestion
            kakao_id                 = user_info['id']
```

2022-05-15 06:38 UTC, Kang-kyunghun commented on users/views.py
> +            access_token = jwt.encode({'id':id, 'exp':datetime.utcnow() + timedelta(days=1)}, SECRET_KEY, algorithm=ALGORITHM)
token을 만들 때 kakao_id를 사용하신 것 같은데, 만약 kakao 로그인만 존재한다면 괜찮은 방법인 것 같습니다. 그런데 일반 로그인이나 다른 소셜로그인을 같이 사용한다면 문제가 될 것 같습니다.
따라서 저희의 user id를 사용하는 것이 좋을 것 같습니다.

2022-05-15 06:39 UTC, Kang-kyunghun commented
수정 사항 적용하시고, 테스트코드 추가해 주세요.

2022-05-16 15:37 UTC, alexms0316 commented on users/views.py
> +from datetime     import datetime, timedelta
넵 알겠습니다!

2022-05-16 15:40 UTC, alexms0316 commented on users/views.py
> +            user_info_response = requests.get(kakao_info_api,headers=headers, timeout=5)
넵

2022-05-17 02:41 UTC, alexms0316 commented on users/views.py
> +            access_token = jwt.encode({'id':id, 'exp':datetime.utcnow() + timedelta(days=1)}, SECRET_KEY, algorithm=ALGORITHM)
이해를 못했습니다. 나중에 질문 드리겠습니다!

2022-05-19 08:22 UTC, Kang-kyunghun commented
민석님 rebase 후에 커밋 메시지는 해당 브렌치가 궁극적으로 어떤 작업을 나타내는지를 기록해 주셔야 합니다. 지금처럼 일부 작업 내용을 적으면 추후에 알아보기가 힘듭니다. 지금은 일단 merge 하지만 다음 PR부터는 주의해 주세요.

2022-05-19 08:22 UTC, merged